name: Build & Publish
on:
  push:
    branches:
      - "replace_go_crond"
jobs:
  setup-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Check credentials
        id: docker-credentials
        run: |
          echo ::set-output name=defined::$(test -n "${{ secrets.DOCKERHUB_USERNAME }}" && echo true || echo false)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: steps.docker-credentials.outputs.defined == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build-commons:
    runs-on: ubuntu-20.04
    needs: setup-images
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Build and push "commons"
        id: docker_build_commons
        uses: docker/build-push-action@v2
        with:
          context: ./images/commons
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            testlagoon/commons-test:${{ env.GITHUB_REF_SLUG }}
            ghcr.io/uselagoon/commons-test:${{ env.GITHUB_REF_SLUG }}

      - name: Show image digest
        run: |
          echo ${{ steps.docker_build_commons.outputs.digest }}
